### ISSUE TITLE
Incorrect parsing of texture

### ISSUE THREAD

**Issue by nimelord** [Mudbill/dds-lwjgl#8]
There is definitely transparent texture with alpha channel: 
[trees_kamish_big_01.dds.zip](https://github.com/Mudbill/dds-lwjgl/files/15209429/trees_kamish_big_01.dds.zip)

The format of image defined as 0x83f0 instead of 0x83f1.

Specifications of MS says: BC1 - Three-channel color with alpha channel (https://learn.microsoft.com/en-us/windows/win32/direct3d11/texture-block-compression-in-direct3d-11)

That is because of:
`
case DXGI_FORMAT_BC1_UNORM:			return GL_COMPRESSED_RGB_S3TC_DXT1_EXT;
`
Must be:
`
case DXGI_FORMAT_BC1_UNORM:			return GL_COMPRESSED_RGBA_S3TC_DXT1_EXT;
`

As a result I have that:
![error](https://github.com/Mudbill/dds-lwjgl/assets/21811792/93acaa23-8cf3-453b-9111-e0b1453fb02b)
Instead of:
![ok](https://github.com/Mudbill/dds-lwjgl/assets/21811792/ed445ff2-b010-4afd-953e-b3e41a18354e)

PS: Also I can add maven support if You let me do.)

**Comment by Mudbill** [comment]
Thanks for the report, I'll have a look

**Comment by nimelord** [comment]
> Thanks for the report, I'll have a look

Could you let me create branches and PRs?
I can add support of maven.

**Comment by Mudbill** [comment]
> > Thanks for the report, I'll have a look
> 
> Could you let me create branches and PRs? I can add support of maven.

While I'm fairly rusty with Java in general as I haven't touched it much the last few years, I've worked a bit with Gradle as of late. By no means am I an expert, especially when it comes to publishing, but from what I understand, Gradle can also support Maven formats. I don't know much about Maven, so I'm unsure if Maven can do it the other way around. Just based on this, I think I would prefer to go the Gradle way so that it supports both.
That said, I would be happy to receive any suggestions or examples for how to implement it, I just don't want to waste your time in case I end up doing it differently 😅
As a learning experience for myself, I think I would prefer to give it a shot first, but you're free to correct me after.

**Comment by nimelord** [comment]
As you wish)
But I can add pom.xml to support of maven very easily. It requires to set version manually every release build. That all.

The point is when you publish your lib to central maven repo usages of it should be raised up. Because  of gradle and maven devs - both of the groups.
Now if dev needs your lib He must add it as local library - complicated support of such dependency.
Also dependency from lwjgl is requires to but was lost:  which version of lwjgl?
I can say - I'm looking forward to it as a maven library.

Anyway, thank you very much for your lib!
Have a good day! :)

**Comment by Mudbill** [comment]
I will do my best to clarify these things. It has admittedly been a bit vague.
Version of LWJGL looks to be anything of v3. I haven't tested v2 though, but from what I recall there were some limitations.
For now, I have set up a basic test scenario using Gradle that exists in the repo master branch. I will expand on it.
